import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { AsteraFooter } from "./_components/footer/footer";
import { me } from "./lib/auth";
import { AsteraHeader } from "./_components/header/header";
import { cookies } from "next/headers";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const cookie = await cookies();
  const token = cookie.get('token')?.value;
  const auth = await me(token);

  return (
    <html lang="en">
      <body>
        <main>
          <AsteraHeader me={auth} />
          {children}
          <AsteraFooter />
        </main>
      </body>
    </html>
  );
}
